apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: react-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-backend
  template:
    metadata:
      labels:
        app: react-backend
    spec:
      containers:
        - name: react-backend
          image: sadilegend/todo-backend:latest
          ports:
            - containerPort: 6200
