apiVersion: v1
kind: Service
metadata:
  name: backend-todo-svc
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app: react-backend
  ports:
    - name: TCP
      port: 6200
      targetPort: 6200
      nodePort: 32600
